---
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/{{ item }}-{{ vector_version }}-1.x86_64.rpm"
    dest: "./{{ item }}-{{ vector_version }}.rpm"
  loop: "{{ vector_packages }}"

- name: Install vector packages
  become: true
  ansible.builtin.yum:
    name: "{{ item }}-{{ vector_version }}.rpm"
  loop: "{{ vector_packages }}"
  notify: Start vector service